on: [push]

jobs:
  run_integ_tests:
    name: Run integ tests
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    services:
      greetings:
        image: shanelee007/greetings-api:latest
        ports:
          - 8090:8081
      postgres:
        image: postgres:11
        env:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: root
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots test  -Dtest=CustomerGithubActionsIT
      env:
        POSTGRES_HOST: jdbc:postgresql://localhost:5432/postgres
